### ISSUE TITLE
copy and save.

### ISSUE THREAD

**Issue by niksingh710** [reinefjord/wayshot#1]
Liked the Script mate.
Just wanted to know how can i copy the image to clipboard and save it to a dir to in grim? 

any idea?

**Comment by reinefjord** [comment]
I'm glad you found it useful! :)

If you have [wl-clipboard](https://github.com/bugaevc/wl-clipboard) installed, you can use `wayshot -c` to put the image in your clipboard instead of saving it to a file. I don't understand what you mean by "save it to a dir to in grim" though, would you mind rephrasing that?

**Comment by reinefjord** [comment]
I read the title again and got it, you want to simultaneously save the screenshot to clipboard and a file? I've added that now in https://github.com/reinefjord/wayshot/commit/dacd595c36f93602fd5e9d0350163f8e409f2cda! :) Run wayshot with both `-c` and a filename, like `wayshot -c screenshot.png`

**Comment by niksingh710** [comment]
Sorry my bad for explaining but that was what I exactly wanted. Thanks.
